### PR TITLE
261 Fix media export

### LINKED ISSUE #261: Download media files no longer working on test
**Describe the bug**
In the programme script view, after selecting the export option, no modal appears allowing users to download media files after selecting the 'Download media' option

**To Reproduce**
1. Sign in as dpe-admin and go to https://digital-paper-edit.test.tools.bbc.co.uk/#/projects/BBDpT2KIRMPXjY47Ufjj/paperedits/fKuOM1JH9Q0xFfe5qiqc
2. Click on 'Export'
3. Select 'Download media files'
4. See error: no media files will download and no modal will appear

**Expected behavior**

See the live site for expected behaviour: sign in as the admin user and visit https://digital-paper-edit.tools.bbc.co.uk/#/projects/Z1JtmeZRxUYW8hvINDNc/paperedits/BHYic6FIOHmKEf3KVUy4

Screenshot 2021-05-21 at 11 17 32

**Screenshots**

This appears in the logs:

Screenshot 2021-05-21 at 11 16 15

https://digital-paper-edit.test.tools.bbc.co.uk/#/projects/BBDpT2KIRMPXjY47Ufjj/paperedits/fKuOM1JH9Q0xFfe5qiqc

**Additional context**

It seems like it might have something to do with the newest changes to the playlist, based on the error messages above.

### PR DESCRIPTION
**Pull request by allishultes**
**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      

Fixes #261 

**Describe what the PR does**    

- [x] Passes storage as a prop to the ExportDropdown element from the ProgrammeScriptContainer

**State whether the PR is ready for review or whether it needs extra work**    

Ready

**Additional context**    

To test: 
- Run the app
- Select the "Download media" option from the "Export" dropdown on this project: http://localhost:3000/#/projects/BBDpT2KIRMPXjY47Ufjj/paperedits/fKuOM1JH9Q0xFfe5qiqc
- Open your media files after download to make sure they play back

Additional issues:
- This errors if your programme script contains references to expired media. Expected behaviour would probably be to present any media you do find, and ignore expired media - or else, in the modal, display expired media with deactivated download buttons. I think this is outside the scope of the ticket as we have lots of functionality around expired media that has not been implemented yet. Run and see: http://localhost:3000/#/projects/Bd6tblAMtbngsjQMnU0C/paperedits/1JjFHzEU7arzrffLhYL8

### CODE REVIEW

File: src/Components/PaperEditor/ProgrammeScriptContainer/utils/compilePlaylist.js [hunk 1]
```diff
@@ -15,7 +15,10 @@ const paperEditsAreContinuous = (lastPlaylistItem, currentEdit) => {
   return areFromSameTranscript && areConsecutiveClips;
 };
 
-const getMediaUrl = async (storage, item) => storage.ref(item.ref).getDownloadURL();
+const getMediaUrl = async (storage, item) => {
+
+  return await storage.ref(item.ref).getDownloadURL();
```
Comment (aniablaziak) [inline src/Components/PaperEditor/ProgrammeScriptContainer/utils/compilePlaylist.js:20]: good spot! 👍

**Review by aniablaziak — APPROVED** [review]
looks good to me :octocat:

**Review by sarahrainbow — APPROVED** [review]
looks awesome ⭐️
